spring.application.name=game
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:1234/game
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver